$Scripts = Get-ChildItem -Path "$PSCommandPath\..\..\registry"

ForEach ($Script in $Scripts) {
    # Test if script signatures are valid
    if ((Get-AuthenticodeSignature $Script.FullName).Status -ne 'Valid') {
        Write-Host $Script
        return $False
    }
}

return $True

# SIG # Begin signature block
# MIIFhQYJKoZIhvcNAQcCoIIFdjCCBXICAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU3Ski7kkx3PH3aCwCTpWcLBQt
# 9gegggMYMIIDFDCCAfygAwIBAgIQQw1cl15poZNEBlXzeuaUrjANBgkqhkiG9w0B
# AQUFADAiMSAwHgYDVQQDDBdDb2xsYXRlIHNjcmlwdHMgc2lnbmluZzAeFw0yMjAy
# MjYxMDEyNDVaFw0yNzAyMjYxMDIyNDRaMCIxIDAeBgNVBAMMF0NvbGxhdGUgc2Ny
# aXB0cyBzaWduaW5nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnu3z
# 1LBnJKjh35fMEhMrS8vHKM02M7s8TeBHc5qgNf02c6cFJrr1piHaDXERhlT7QarN
# 8/7ntkxGQr+YHBOjvlBnLOOxEQ1QEW3tHIlxo7q3UqEAtpuFwmFUmPJuQT6/fIW3
# Aymx7+4xP32QPujJAKWDcdLMLhWRJr4K7I31RzSxQalLVDg61MwIP3nUiSPi0hxW
# IKohzNQpLmv0l+XS6mizvQOBVt27VnZpQqqaRbV2ZZi3rASwTUgPsn9hmMMyfWP2
# lnHamTkGdwsW4wk/QLAfJTdT+qeTw9bx9TaM7DNDbB14HHen6omWRly5gF3eLrgu
# CZ4I10USjQUaxPdZxQIDAQABo0YwRDAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwHQYDVR0OBBYEFE1uz/xKJu5JYkpGkY8olpKfRKDKMA0GCSqG
# SIb3DQEBBQUAA4IBAQBwFFH2tIO1DpJU9pDFNkN2RQKJPLSraP8EF+05HhSOh0ka
# dkPR2kNWv6oX2MBXXzsWobbhbqD4+CU36zU9ciHWoNGRE2rkw/Umo6cPoAAiFH4+
# kx1HVqy7QY05g6FTM+kfB/C/1+EbRsGCCwWviEEzsEFivHH2pKC5RJFUKhTQLC6m
# SadNM7X9njEBs4uSqQWDLbkHWWoeS0ddc+xZF0WhJhiQZck26cwbzFmdSXW45J4j
# KaJv/SI+Z7EHo08BRUN0Ad7kTDPEE68WrIyxoe4NQ4KFPJzFFbl5/ydTJF0J1VpP
# CdHBRj15ItXmm9vPnn/9bLsBSDB18mwd+b532penMYIB1zCCAdMCAQEwNjAiMSAw
# HgYDVQQDDBdDb2xsYXRlIHNjcmlwdHMgc2lnbmluZwIQQw1cl15poZNEBlXzeuaU
# rjAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG
# 9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIB
# FTAjBgkqhkiG9w0BCQQxFgQUFRs23FDK4TUk8AcwelNCSg3j8a8wDQYJKoZIhvcN
# AQEBBQAEggEAHKZa6gKK3I0LPqcNdbKzXpx8pupfHR+r4Wnni1ZubHheOKWvA08+
# 98h2dM7DQ3eG5dbDnGiCCn62JLGtlRQWrdOJrHcpwh7ysGhAGeuzIhr8GdKKH/Y9
# kO23hS6cWMTMMM99CW88MFV3GmDsQp2b+tYi7Q18cNciopNw+B3t3/Hep11BX+Bz
# SdipmvlAzLFKOf1WnLKO1e6Ouqg2ugzq79CmVwk8l+uC4IQlo+dO3zD7wWhIX4Fs
# lRY6dzDOZSQWFVJ8mHt0JnoIhzamj5Vek9IUBN+aNy8ir4YkhM/RVjPxoI+KP2lW
# FToFjWcmkgWF7zMyty1iZTnUQE0lxKulYw==
# SIG # End signature block
